version: "3.8"
services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.web
      target: development
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://service:4000/graphql
      - NODE_ENV=development
    volumes:
      - ../web:/app/web
      - /app/web/node_modules
    command: pnpm dev
    depends_on:
      service:
        condition: service_started
      mysql:
        condition: service_healthy
    networks:
      - app-network

  service:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.service
      target: development
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=on_musubi
      - DB_USER=user
      - DB_PASSWORD=password
    volumes:
      - ../service:/app/service
      - /app/service/node_modules
    command: pnpm dev
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: on_musubi
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  app-network:
    name: app-network
    driver: bridge
