# 開発環境
FROM node:18-slim as development

WORKDIR /app/service

RUN npm install -g pnpm

COPY service/package.json service/pnpm-lock.yaml ./

RUN ls -l /app/service

RUN pnpm install

EXPOSE 4000



# 本番環境
FROM node:18-slim as production

WORKDIR /app/service

RUN npm install -g pnpm

COPY service/package.json service/pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY service/ ./

ENV NODE_ENV production

CMD ["pnpm", "start"]
